import pywintypes
from win32com.shell import shell, shellcon
# generated by AI

def get_special_folder_path(csidl):
  """Retrieves the path of a special folder using SHGetSpecialFolderLocation and SHGetPathFromIDList."""
  try:
    pidl = shell.SHGetSpecialFolderLocation(0, csidl)
    path = shell.SHGetPathFromIDList(pidl)
    return path
  except pywintypes.error as e:
    print(f"Error getting special folder path: {e}")
    return None

# Get and print the AppData path
appdata_path = get_special_folder_path(shellcon.CSIDL_APPDATA)
if appdata_path:
  print(f"AppData Path: {appdata_path}")

# Get and print the My Documents path
documents_path = get_special_folder_path(shellcon.CSIDL_PERSONAL)
if documents_path:
  print(f"My Documents Path: {documents_path}")